# Project 04 -- [Pavan Kumar] [Battula]

**TA Help:** N/A

- Help with figuring out how to write a function.
    
**Collaboration:** N/A    
- Helped figuring out how to load the dataset.
- Helped debug error with my plot.

## Question 1

In [1]:
import pandas as pd

In [2]:
myDF = pd.read_csv("/anvil/projects/tdm/data/noaa/1880.csv", header = None, names=["id","date","element_code","value","mflag","qflag","sflag","obstime"])

In [3]:
myDF.head()

id      date element_code  value mflag qflag sflag  obstime
0  AGE00147705  18800101         PRCP      0   NaN   NaN     E      NaN
1  AGE00147708  18800101         PRCP     36   NaN   NaN     E      NaN
2  AGE00147709  18800101         PRCP     36   NaN   NaN     E      NaN
3  AGE00147712  18800101         PRCP      0   NaN   NaN     E      NaN
4  AGE00147713  18800101         TMAX     52   NaN   NaN     E      NaN

In [ ]:
for index, row in myDF.iterrows():
    if row['element_code'] == 'PRCP':
        if row['value'] >= 1200:
            print(row['date'])

In [ ]:
myDF[(myDF['element_code'] == 'PRCP') & (myDF['value'] >= 1200) ]['date']

The second approach is faster and understood better.

## Question 2

In [10]:
from pathlib import Path
Path ("/anvil/projects/tdm/data/noaa")

PosixPath('/anvil/projects/tdm/data/noaa')

In [11]:
myfiles = [Path(f'/anvil/projects/tdm/data/noaa/{year}.csv') for year in range(1800, 1851)]
myfiles

[PosixPath('/anvil/projects/tdm/data/noaa/1800.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1801.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1802.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1803.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1804.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1805.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1806.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1807.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1808.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1809.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1810.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1811.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1812.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1813.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1814.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1815.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1816.csv'),
 PosixPath('/anvil/projects/tdm/data/noaa/1817.csv'),
 PosixPath('/anvil/projects/

In [12]:
import pandas as pd
from pathlib import Path

myfiles = [Path(f'/anvil/projects/tdm/data/noaa/{year}.csv') for year in range(1800, 1851)]

for filepath in myfiles:
   
    length = 0
    total = 0

    year = int(filepath.stem)  
    year2= year;
    myDF = pd.read_csv(filepath, header = None, names=["id","date","element_code","value","mflag","qflag","sflag","obstime"]) 

    for index, row in myDF.iterrows():
        if (row['element_code'] == 'PRCP') & ( year2 == year):
            length += 1
            total += row['value']
    avg = total / length
       
    print(f'Year: {year}, Average Precipitation: {avg}')
    

Year: 1800, Average Precipitation: 16.016438356164382
Year: 1801, Average Precipitation: 19.416438356164385
Year: 1802, Average Precipitation: 11.37945205479452
Year: 1803, Average Precipitation: 19.63013698630137
Year: 1804, Average Precipitation: 16.968903436988544
Year: 1805, Average Precipitation: 13.963013698630137
Year: 1806, Average Precipitation: 13.481361426256077
Year: 1807, Average Precipitation: 15.396825396825397
Year: 1808, Average Precipitation: 16.23633879781421
Year: 1809, Average Precipitation: 14.687671232876712
Year: 1810, Average Precipitation: 14.23489010989011
Year: 1811, Average Precipitation: 12.754794520547945
Year: 1812, Average Precipitation: 15.904371584699453
Year: 1813, Average Precipitation: 22.049397590361444
Year: 1814, Average Precipitation: 21.04501216545012
Year: 1815, Average Precipitation: 24.774074074074075
Year: 1816, Average Precipitation: 20.02589395807645
Year: 1817, Average Precipitation: 20.357409713574096
Year: 1818, Average Precipitation:

In [47]:
year_index = 0


while year_index < len(myfiles):
    filepath = myfiles[year_index]
    length = 0
    total = 0

    year = int(filepath.stem) 
    myDF = pd.read_csv(filepath, header=None, names=["id", "date", "element_code", "value", "mflag", "qflag", "sflag", "obstime"])

    for index, row in myDF.iterrows():
        if row['element_code'] == 'PRCP':
            length += 1
            total += row['value']
    avg = total / length

    if avg < 22:
        print(f'Year: {year}, Average Precipitation: {avg}')
    else:
        break

    year_index += 1

Year: 1800, Average Precipitation: 16.016438356164382
Year: 1801, Average Precipitation: 19.416438356164385
Year: 1802, Average Precipitation: 11.37945205479452
Year: 1803, Average Precipitation: 19.63013698630137
Year: 1804, Average Precipitation: 16.968903436988544
Year: 1805, Average Precipitation: 13.963013698630137
Year: 1806, Average Precipitation: 13.481361426256077
Year: 1807, Average Precipitation: 15.396825396825397
Year: 1808, Average Precipitation: 16.23633879781421
Year: 1809, Average Precipitation: 14.687671232876712
Year: 1810, Average Precipitation: 14.23489010989011
Year: 1811, Average Precipitation: 12.754794520547945
Year: 1812, Average Precipitation: 15.904371584699453


## Question 3

In [51]:
myDF = pd.read_csv("/anvil/projects/tdm/data/noaa/1880.csv", header = None, names=["id","date","element_code","value","mflag","qflag","sflag","obstime"])


In [52]:
myDF[myDF['element_code'] == 'PRCP'].groupby('id')['value'].mean().sort_values().max()

610.0

In [53]:
myDF[myDF['element_code'] == 'PRCP'].groupby('id')['value'].mean().sort_values()

id
USC00308138      0.000000
ASN00033054      0.000000
ASN00033050      0.000000
ASN00033046      0.000000
ASN00033007      0.000000
                  ...    
USC00314055     88.978632
USC00316001    103.685039
USC00315838    112.875000
USC00012207    151.290698
USC00483073    610.000000
Name: value, Length: 744, dtype: float64

the id of maximum average percipitation is  : USC00483073    610.000000.

In [54]:
myDF[myDF['element_code'] == 'PRCP'].groupby('id')['value'].mean().sort_values()['USC00288878']

35.08516483516483

the id USC00288878's average percipitation is 35.08516483516483.

## Question 4

In [57]:
myDF[myDF['element_code'] == 'PRCP'].groupby('id')['value'].mean().sort_values().to_dict()

{'USC00308138': 0.0,
 'ASN00033054': 0.0,
 'ASN00033050': 0.0,
 'ASN00033046': 0.0,
 'ASN00033007': 0.0,
 'ASN00033005': 0.0,
 'ASN00032047': 0.0,
 'ASN00032004': 0.0,
 'ASN00030036': 0.0,
 'ASN00030018': 0.0,
 'ASN00029072': 0.0,
 'ASN00029041': 0.0,
 'ASN00033065': 0.0,
 'ASN00029019': 0.0,
 'ASN00043030': 0.0,
 'ASN00026016': 0.0,
 'ASN00044004': 0.0,
 'ASN00024573': 0.0,
 'ASN00024531': 0.0,
 'ASN00023795': 0.0,
 'ASN00023782': 0.0,
 'ASN00023773': 0.0,
 'ASN00023068': 0.0,
 'ASN00044026': 0.0,
 'ASN00045014': 0.0,
 'ASN00043022': 0.0,
 'ASN00045017': 0.0,
 'ASN00035019': 0.0,
 'ASN00035049': 0.0,
 'ASN00041038': 0.0,
 'ASN00041023': 0.0,
 'ASN00041013': 0.0,
 'ASN00040358': 0.0,
 'ASN00040242': 0.0,
 'ASN00040226': 0.0,
 'ASN00040225': 0.0,
 'ASN00042071': 0.0,
 'ASN00040126': 0.0,
 'ASN00040111': 0.0,
 'ASN00040101': 0.0,
 'ASN00035037': 0.0,
 'ASN00040096': 0.0,
 'ASN00040047': 0.0,
 'ASN00040016': 0.0,
 'ASN00039041': 0.0,
 'ASN00039039': 0.0,
 'ASN00039022': 0.0,
 'ASN00039003

Markdown notes and sentences and analysis written here.

## Question 5

In [1]:
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/youtube/DEvideos.csv")
myDF.head()

video_id trending_date  \
0  LgVi6y5QIjM      17.14.11   
1  Bayt7uQith4      17.14.11   
2  1ZAPwfrtAFY      17.14.11   
3  AHtypnRk7JE      17.14.11   
4  ZJ9We4bjcg0      17.14.11   

                                               title            channel_title  \
0  Sing zu Ende! | Gesangseinlagen vom Feinsten |...                inscope21   
1  Kinder ferngesteuert im Kiosk! Erwachsene abzo...  LUKE! Die Woche und ich   
2  The Trump Presidency: Last Week Tonight with J...          LastWeekTonight   
3                                Das Fermi-Paradoxon        100SekundenPhysik   
4           18 SONGS mit Kelly MissesVlog (Sing-off)                     rezo   

   category_id              publish_time  \
0           24  2017-11-13T17:08:49.000Z   
1           23  2017-11-12T22:30:01.000Z   
2           24  2017-11-13T07:30:00.000Z   
3           27  2017-11-12T15:00:01.000Z   
4           24  2017-11-12T13:10:36.000Z   

                                                tags    views   likes  \
0  inscope21|"sing zu ende"|"gesangseinlagen"|"ge...   252786   35885   
1  Kinder|"ferngesteuert"|"Kinder ferngesteuert"|...   797196   53576   
2  last week tonight trump presidency|"last week ...  2418783   97190   
3  Physik|"Wissenschaft"|"Technik"|"Science-Ficti...   380247   31821   
4  kelly|"missesvlog"|"kelly song"|"bausa"|"bausa...   822213  100684   

   dislikes  comment_count                                  thumbnail_link  \
0       230           1539  https://i.ytimg.com/vi/LgVi6y5QIjM/default.jpg   
1       302           1278  https://i.ytimg.com/vi/Bayt7uQith4/default.jpg   
2      6146          12703  https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg   
3       458           1955  https://i.ytimg.com/vi/AHtypnRk7JE/default.jpg   
4      2467          10244  https://i.ytimg.com/vi/ZJ9We4bjcg0/default.jpg   

   comments_disabled  ratings_disabled  video_error_or_removed  \
0              False             False                   False   
1              False             False                   False   
2              False             False                   False   
3              False             False                   False   
4              False             False                   False   

                                         description  
0  Heute gibt es mal wieder ein neues Format... w...  
1  Kinder ferngesteuert! Kinder lassen sich sooo ...  
2  One year after the presidential election, John...  
3  ►Alle Videos: http://bit.ly/1fa7Tw3\n\n\n✚Snap...  
4  18 Song Mashup über den (veränderten) Beat von...

In [2]:
  count = 0
for index, row in myDF.iterrows():
    if (row['likes'] >= 2000000):
            count += 1
             
print(f'Total number of DEvideos liked more than 2M: {count}')

Total number of DEvideos liked more than 2M: 20


Total number of DEvideos liked more than 2M: 20

In [3]:
count = 0
index = 0
while index < len(myDF):
    for index, row in myDF.iterrows():
        if (row['dislikes'] >= 2000):
            count += 1
        index += 1;
             
print(f'Total number of videos disliked more than 2k: {count}')

Total number of videos disliked more than 2k: 3958


Total number of videos disliked more than 2k: 3958

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.